version: 2.1

jobs:
  build:
    docker:
      - image: ruby:3.1.2
      - image: postgres:latest
        environment:
          POSTGRES_PASSWORD: your_password_here  # Set your desired PostgreSQL password

    environment:
      RAILS_ENV: test

    working_directory: /app

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

      - run:
          name: Set up PostgreSQL
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate

      - run:
          name: Build and test
          command: |
            bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
