version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.2  # Use the desired Ruby version

    working_directory: /app  # Set your working directory

    steps:
      - checkout  # Check out your source code

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

      - run:
          name: Build and test
          command: |
            # Replace these commands with your build and test commands
            # For example, you might run 'rspec' or 'rails test'
            ruby --version
            bundle exec rspec

# You can add more jobs or workflows as needed
