version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.2

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

